import Report from "../models/Report.js";
import asyncHandler from "../middleware/asyncHandler.js";
import { sendSuccess, ApiError } from "../utils/apiResponse.js";

/**
 * @desc    Manually create a report (legacy/manual path - reports are
 *          normally auto-generated by roomController.endSession)
 * @route   POST /api/reports
 * @access  Private (teacher)
 */
export const createReport = asyncHandler(async (req, res) => {
  const report = await Report.create({
    ...req.body,
    teacher: req.user._id,
  });

  sendSuccess(res, 201, "Report created successfully", report);
});

/**
 * @desc    Get all reports belonging to the logged-in teacher
 * @route   GET /api/reports
 * @access  Private (teacher)
 */
export const getReports = asyncHandler(async (req, res) => {
  const reports = await Report.find({ teacher: req.user._id })
    .sort({ createdAt: -1 })
    .select("-attentionGraphData -exportableData -timelineData"); // keep list view light

  sendSuccess(res, 200, "Reports fetched successfully", reports);
});

/**
 * @desc    Get a single report by id (full detail, including graph data)
 * @route   GET /api/reports/:id
 * @access  Private (teacher, must own the report)
 */
export const getReportById = asyncHandler(async (req, res) => {
  const report = await Report.findById(req.params.id);

  if (!report) {
    throw new ApiError(404, "Report not found");
  }

  if (report.teacher.toString() !== req.user._id.toString()) {
    throw new ApiError(403, "You are not authorized to view this report");
  }

  sendSuccess(res, 200, "Report fetched successfully", report);
});

/**
 * @desc    Delete a report
 * @route   DELETE /api/reports/:id
 * @access  Private (teacher, must own the report)
 */
export const deleteReport = asyncHandler(async (req, res) => {
  const report = await Report.findById(req.params.id);

  if (!report) {
    throw new ApiError(404, "Report not found");
  }

  if (report.teacher.toString() !== req.user._id.toString()) {
    throw new ApiError(403, "You are not authorized to delete this report");
  }

  await report.deleteOne();

  sendSuccess(res, 200, "Report deleted successfully", null);
});